"""
Configuration package initialization.
"""

from .settings import *

__all__ = [
    "WORDLISTS_DIR",
    "NAMES_TO_INCLUDE_FILE",
    "NON_PERSONAL_NAMES_TO_INCLUDE",
    "WORDS_TO_INCLUDE_FILE",
    "WORDS_TO_REMOVE_FILE",
    "DEFAULT_SOURCE_FOLDER",
    "DEFAULT_TARGET_FOLDER",
    "DEFAULT_MAX_FILENAME_LENGTH",
    "DEFAULT_RATE_LIMIT_PER_MINUTE",
    "SPACY_MODEL",
    "NER_CATEGORIES",
    "OLLAMA_MODEL_DESCRIPTION",
    "OLLAMA_MODEL_KEYWORDS",
    "OLLAMA_NUM_GPU",
    "OLLAMA_NUM_CPU",
    "OLLAMA_MIN_SECONDS_BETWEEN_CALLS",
    "OLLAMA_MAX_RETRIES",
    "OLLAMA_RETRY_BACKOFF_SECONDS",
    "OCR_LANGUAGES",
    "DATE_PATTERNS",
    "ILLEGAL_CHARS",
    "WORD_VARIANTS",
    "OCR_CORRECTIONS",
]
